{% set version = "1.7.0" %}

package:
  name: tabby-agent
  version: {{ version }}

source:
  url: https://registry.npmjs.org/tabby-agent/-/tabby-agent-{{ version }}.tgz
  sha256: 8c08f00c55d1629dbc6bd5ff1d64ae82d3ea6083dcab2d6512ff06d50ff4f61c

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
  run:
    - nodejs

test:
  commands:
    - tabby-agent --node-ipc &
    - exe_pid=$!
    - "trap \"kill -SIGTERM ${exe_pid}\" SIGTERM"

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: Self-hosted AI coding assistant
  home: https://github.com/TabbyML/tabby
  dev_url: https://github.com/TabbyML/tabby

extra:
  recipe-maintainers:
    - danielnachun
